services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kupe-house-website-api
    container_name: kupe-house-site-api-server
    ports:
      - "54340:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./app:/app
    networks:
      - flask-network
    restart: always

networks:
  flask-network:
    driver: bridge
