services:
  flask-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: kupe-facts-api-flask-app
    ports:
      - "54340:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - ./app:/app
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
